# Generated by Django 5.1.6 on 2025-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_birth_date_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
